# synthesizer/prompt/context_channels.py
"""Context channel packaging for generation prompts (§13).

Three structured context channels carry information into generation prompts:
  1. Claim tables (§13.1) — from upstream content dependencies
  2. Summary abstracts (§13.2) — from upstream thematic dependencies
  3. Evidence pointers (§13.3) — from Stage 05 retrieval

Raw upstream prose (content_markdown) is explicitly excluded (DR-03, FR-12).
Stage 05 answer text is explicitly excluded (DR-05, FR-10).
Stage 06 summaries are explicitly excluded (DR-06).
"""

from __future__ import annotations

from typing import Dict, List, Optional

from synthesizer.models.claims import ClaimTable
from synthesizer.retrieval.adapter import RankedChunk


# ---------------------------------------------------------------------------
# §13.1  Claim table packaging (content dependencies)
# ---------------------------------------------------------------------------

def package_claim_tables(
    upstream_claim_tables: Dict[str, ClaimTable],
) -> str:
    """Serialize upstream claim tables for insertion into a generation prompt.

    Each claim table comes from a finalized upstream section that the
    current section has a content dependency on (§13.1). The downstream
    section must engage with the claims contained therein.

    Parameters
    ----------
    upstream_claim_tables : dict
        Maps upstream section_id → ClaimTable. Only tables from content
        dependencies should be passed here.

    Returns
    -------
    str
        Formatted text block for prompt insertion. Empty string if no
        claim tables are provided.

    Notes
    -----
    DR-03: Raw upstream prose is excluded. Only structured claim data
    is serialized — never the upstream section's content_markdown.
    """
    if not upstream_claim_tables:
        return ""

    parts: List[str] = []
    parts.append("=== UPSTREAM CLAIM TABLES (Content Dependencies) ===")
    parts.append(
        "The following claims are from upstream sections that this section "
        "depends on. You must engage with these claims in your synthesis."
    )

    for section_id in sorted(upstream_claim_tables):
        ct = upstream_claim_tables[section_id]
        parts.append(f"\n--- Claims from section: {section_id} ---")

        if ct.partial:
            parts.append(
                "[WARNING: This claim table is partial — extraction was "
                "incomplete. Some claims may be missing.]"
            )

        if not ct.claims:
            parts.append("(No claims extracted.)")
            continue

        for claim in ct.claims:
            parts.append(
                f"  [{claim.claim_id}] {claim.claim_text}\n"
                f"    Confidence: {claim.confidence_tag.value}\n"
                f"    Source chunks: {', '.join(claim.source_chunk_ids)}"
            )

    parts.append("\n=== END UPSTREAM CLAIM TABLES ===")
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# §13.2  Summary abstract packaging (thematic dependencies)
# ---------------------------------------------------------------------------

def package_summary_abstracts(
    upstream_abstracts: Dict[str, str],
) -> str:
    """Serialize upstream summary abstracts for insertion into a generation prompt.

    Summary abstracts are 2-3 sentence summaries generated by the
    Summary Abstractifier (§9.2.4) from upstream sections. They provide
    high-level thematic context for sections with thematic (or content)
    dependencies (§13.2).

    Parameters
    ----------
    upstream_abstracts : dict
        Maps upstream section_id → summary abstract string. Only
        abstracts from thematic and content dependencies should be
        passed here.

    Returns
    -------
    str
        Formatted text block for prompt insertion. Empty string if no
        abstracts are provided.

    Notes
    -----
    DR-03: These are summary abstracts — NOT raw upstream prose.
    The full content_markdown of upstream sections is never included.
    """
    if not upstream_abstracts:
        return ""

    parts: List[str] = []
    parts.append("=== UPSTREAM SUMMARY ABSTRACTS (Thematic Context) ===")
    parts.append(
        "The following summaries provide thematic context from related "
        "sections. Use them to maintain narrative coherence."
    )

    for section_id in sorted(upstream_abstracts):
        abstract = upstream_abstracts[section_id]
        parts.append(f"\n--- Summary of section: {section_id} ---")
        parts.append(abstract.strip())

    parts.append("\n=== END UPSTREAM SUMMARY ABSTRACTS ===")
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# §13.3  Evidence pointer packaging (retrieval chunks)
# ---------------------------------------------------------------------------

def package_evidence_chunks(
    chunks: List[RankedChunk],
) -> str:
    """Serialize ranked retrieval chunks for insertion into a generation prompt.

    Evidence pointers are the primary evidence base for generation (§13.3).
    Each chunk includes its ID, text, metadata, and retrieval score.

    Parameters
    ----------
    chunks : list of RankedChunk
        Ranked chunks from Stage 05 retrieval, already aggregated and
        deduplicated (FR-09). Answer text has already been discarded
        (FR-10, DR-05).

    Returns
    -------
    str
        Formatted text block for prompt insertion. Empty string if no
        chunks are provided.

    Notes
    -----
    FR-10, DR-05: Only chunk data is included. Stage 05 answer text
    has been discarded at the retrieval adapter layer and does not
    appear anywhere in the output of this function.
    """
    if not chunks:
        return ""

    parts: List[str] = []
    parts.append("=== EVIDENCE CHUNKS (Retrieved from Source Documents) ===")
    parts.append(
        "The following evidence chunks are retrieved from the source "
        "documents. Ground your synthesis in this evidence. Cite "
        "chunks by their IDs."
    )

    for i, chunk in enumerate(chunks, 1):
        meta_parts: List[str] = []
        if chunk.metadata.get("paper_title"):
            meta_parts.append(f"Paper: {chunk.metadata['paper_title']}")
        if chunk.metadata.get("authors"):
            meta_parts.append(f"Authors: {chunk.metadata['authors']}")
        if chunk.metadata.get("year"):
            meta_parts.append(f"Year: {chunk.metadata['year']}")
        if chunk.metadata.get("section"):
            meta_parts.append(f"Section: {chunk.metadata['section']}")

        meta_str = " | ".join(meta_parts) if meta_parts else "No metadata"

        parts.append(
            f"\n--- Chunk {i}: {chunk.id} "
            f"(score: {chunk.score:.4f}, rrf: {chunk.rrf_score:.4f}) ---"
        )
        parts.append(f"Metadata: {meta_str}")
        parts.append(f"Text:\n{chunk.text}")

    parts.append("\n=== END EVIDENCE CHUNKS ===")
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Formatting helpers for style constraints
# ---------------------------------------------------------------------------

def package_style_constraints(
    tone_register: str,
    citation_pattern: str,
    forbidden_phrases: List[str],
    min_words: Optional[int] = None,
    max_words: Optional[int] = None,
    heading_format: Optional[str] = None,
    equation_inline: str = "$",
    equation_display: str = "$$",
    per_type_overrides: Optional[Dict[str, object]] = None,
) -> str:
    """Format style sheet constraints for prompt insertion (§9.2.1).

    Parameters
    ----------
    tone_register : str
        Required tone (e.g., "formal_academic").
    citation_pattern : str
        Regex pattern for valid citations.
    forbidden_phrases : list of str
        Phrases that must not appear.
    min_words : int, optional
        Minimum word count for this section's depth level.
    max_words : int, optional
        Maximum word count for this section's depth level.
    heading_format : str, optional
        Expected heading format (e.g., "##").
    equation_inline : str
        Inline equation delimiter.
    equation_display : str
        Display equation delimiter.
    per_type_overrides : dict, optional
        Type-specific overrides from the style sheet.

    Returns
    -------
    str
        Formatted style constraint block.
    """
    parts: List[str] = []
    parts.append("=== STYLE CONSTRAINTS ===")
    parts.append(f"Tone register: {tone_register}")
    parts.append(f"Citation format (regex): {citation_pattern}")

    if min_words is not None and max_words is not None:
        parts.append(f"Word count range: {min_words}–{max_words} words")
    elif max_words is not None:
        parts.append(f"Maximum word count: {max_words} words")

    if heading_format:
        parts.append(f"Heading format: {heading_format}")

    parts.append(f"Equation delimiters: inline={equation_inline}, display={equation_display}")

    if forbidden_phrases:
        parts.append(f"Forbidden phrases (do NOT use): {', '.join(repr(p) for p in forbidden_phrases)}")

    if per_type_overrides:
        parts.append(f"Type-specific overrides: {per_type_overrides}")

    parts.append("=== END STYLE CONSTRAINTS ===")
    return "\n".join(parts)


def package_retry_errors(
    error_descriptions: List[str],
    layer_name: str,
) -> str:
    """Format validation errors for a retry prompt (FR-15, FR-17).

    Parameters
    ----------
    error_descriptions : list of str
        Error/violation descriptions from the failing validation layer.
    layer_name : str
        Name of the validation layer that failed.

    Returns
    -------
    str
        Formatted error feedback block. Empty string if no errors.
    """
    if not error_descriptions:
        return ""

    parts: List[str] = []
    parts.append(f"=== VALIDATION ERRORS ({layer_name}) ===")
    parts.append(
        "Your previous output failed validation. Please fix the "
        "following issues in your regenerated output:"
    )
    for i, desc in enumerate(error_descriptions, 1):
        parts.append(f"  {i}. {desc}")
    parts.append("=== END VALIDATION ERRORS ===")
    return "\n".join(parts)